import random
from words import random_words


def giveTheWord(random_words):
    autoGenerated = random.choice(random_words)
    return autoGenerated.upper()


dashes = []
already_Entered = []
not_guessed_right = []

my_word = giveTheWord(random_words)
broken_word = [*my_word]    # breaking the word into pieces
dashes = ['?' for i in range(len(broken_word))]  # list comprehension
lives = int(len(broken_word))*2

print()
print(dashes)
print(broken_word)
print(f'You have {lives} tries available!, kaafi hain?')

while lives != 0:
    if len(broken_word) == len(already_Entered):
        print('\nHurrah! You have guessed the word correctly!')
        break           # this is to break when the user has guessed all the characters

    userCharacter = input('\nGuess a character : ').upper()

    if userCharacter in already_Entered:
        print('\nYou have guessed this character already!')
        continue

    lives -= 1

    for i in range(len(broken_word)):
        if userCharacter == broken_word[i]:
            dashes[i] = broken_word[i]

            print('\nYou guessed right!')
            print(f'{lives} tries remaining!\n')
            print(dashes)                   # dashes list has beeen updated
            already_Entered.append(userCharacter)
            print('Characters you guessed right : ', already_Entered)

    else:
        not_guessed_right.append(userCharacter)
        print('\nCharacters you guessed wrong :', not_guessed_right)
        print(f'Not Right! {lives} tries remaining!')

print(f'\nThe letter was this : {my_word}\n')
